version: '3.7'

services:
  database:        
    build:
      context: .
      args:
        root_password: password
    image: database
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/docker_log/database:/var/log/
      - /home/docker_home/database/:/var/lib/mysql

networks:
  default:
    external:
      name: default_bridge
